package com.aikb.ime.pinyin

/** 轻量拼音词库：拼音 → 汉字列表（高频优先） */
object PinyinDict {

    private val dict = mapOf(
        // === 单字 ===
        "a" to listOf("啊", "阿"),
        "ai" to listOf("爱", "哎", "唉", "哀"),
        "an" to listOf("按", "安", "俺"),
        "ang" to listOf("昂", "抗", "康", "忙", "让", "望"),
        "ao" to listOf("奥", "傲", "熬", "凹"),
        "ba" to listOf("吧", "爸", "把", "八", "巴"),
        "bai" to listOf("白", "百", "摆", "败", "拜"),
        "ban" to listOf("班", "搬", "般", "板"),
        "bang" to listOf("帮", "棒", "绑", "胖", "忙", "忙"),
        "bao" to listOf("包", "报", "保", "宝", "抱", "暴"),
        "bei" to listOf("被", "北", "贝", "备", "背"),
        "ben" to listOf("本", "奔", "笨"),
        "beng" to listOf("崩", "泵", "蹦"),
        "bi" to listOf("比", "必", "鼻", "笔", "闭", "币", "毕"),
        "bian" to listOf("变", "边", "编", "遍", "便", "辩"),
        "biao" to listOf("表", "标", "彪", "超"),
        "bie" to listOf("别", "鳖"),
        "bin" to listOf("宾", "滨", "冰", "兵"),
        "bing" to listOf("冰", "并", "病", "丙"),
        "bo" to listOf("不", "波", "博", "拨", "伯"),
        "bu" to listOf("不", "布", "步", "部", "补", "捕", "不", "怖", "赴"),

        "ca" to listOf("擦"),
        "cai" to listOf("才", "菜", "采", "裁", "财"),
        "can" to listOf("参", "餐", "惨", "残"),
        "cang" to listOf("藏", "仓", "苍"),
        "cao" to listOf("草", "操", "草", "曹", "糙"),
        "ce" to listOf("测", "策", "侧", "册"),
        "cen" to listOf("参", "岑"),
        "ceng" to listOf("层", "增"),
        "cha" to listOf("查", "茶", "差", "刹", "叉"),
        "chai" to listOf("拆", "柴", "差"),
        "chan" to listOf("参", "产", "颤", "缠", "蝉"),
        "chang" to listOf("长", "常", "场", "唱", "厂", "尝", "伤", "商", "肠", "当", "党", "当"),
        "chao" to listOf("朝", "超", "炒", "潮", "吵", "逃", "岛"),
        "che" to listOf("车", "扯", "撤"),
        "chen" to listOf("臣", "晨", "陈", "沉", "辰", "神", "深", "审", "真", "珍"),
        "cheng" to listOf("成", "程", "诚", "承", "城", "乘", "撑", "绳", "声", "胜", "生", "升", "剩"),
        "chi" to listOf("吃", "迟", "尺", "赤", "翅", "持", "池", "池", "翅"),
        "chong" to listOf("重", "冲", "虫", "崇", "崇"),
        "chou" to listOf("抽", "愁", "丑", "筹", "周", "州", "舟", "洲"),
        "chu" to listOf("出", "除", "初", "楚", "处", "储", "础", "础"),
        "chua" to listOf("刷"),
        "chuan" to listOf("传", "穿", "船", "川", "串"),
        "chuang" to listOf("创", "床", "窗", "窗"),
        "chui" to listOf("吹", "垂"),
        "chun" to listOf("春", "纯", "淳", "蠢"),
        "chuo" to listOf("错", "措", "绰", "卓"),

        "ci" to listOf("次", "此", "词", "慈", "辞", "磁", "雌"),
        "con" to listOf(""),
        "cong" to listOf("从", "丛", "聪"),
        "cou" to listOf("凑"),
        "cu" to listOf("粗", "促", "醋", "促"),
        "cuan" to listOf("穿", "窜"),
        "cui" to listOf("催", "摧", "脆", "翠"),
        "cun" to listOf("村", "存", "寸", "春"),
        "cuo" to listOf("错", "措", "醋", "措"),

        "da" to listOf("大", "打", "达", "答", "搭"),
        "dai" to listOf("代", "戴", "待", "带", "大"),
        "dan" to listOf("单", "但", "丹", "弹", "担", "淡"),
        "dang" to listOf("当", "党", "挡", "当", "荡"),
        "dao" to listOf("到", "道", "倒", "刀", "岛", "导", "盗", "稻"),
        "de" to listOf("的", "得", "德"),
        "dei" to listOf("得"),
        "deng" to listOf("等", "灯", "登"),
        "di" to listOf("地", "的", "低", "底", "第", "弟", "敌", "笛", "帝", "丢"),
        "dia" to listOf("打"),
        "dian" to listOf("电", "点", "短", "段", "断", "店", "垫", "殿", "佃"),
        "diao" to listOf("调", "掉", "掉", "钓", "叼", "掉"),
        "die" to listOf("跌", "爹", "叠", "碟"),
        "ding" to listOf("定", "丁", "顶", "听", "灯", "订"),
        "diu" to listOf("丢"),
        "dong" to listOf("东", "动", "懂", "冬", "洞", "栋"),
        "dou" to listOf("都", "斗", "豆", "抖", "痘"),
        "du" to listOf("都", "读", "都", "堵", "毒", "杜", "度"),
        "dai" to listOf("带", "大"),
        "dan" to listOf("但", "单", "蛋", "旦", "淡"),
        "dang" to listOf("当", "党", "挡"),
        "dao" to listOf("到", "道", "倒", "刀", "岛", "导"),
        "de" to listOf("的", "得", "德"),
        "dei" to listOf("得"),
        "deng" to listOf("等", "灯", "登"),
        "di" to listOf("地", "第", "弟", "底", "敌", "笛"),
        "dian" to listOf("电", "点", "段", "断", "店"),
        "diao" to listOf("调", "掉", "钓", "叼"),
        "die" to listOf("跌", "爹", "叠"),
        "ding" to listOf("定", "丁", "顶", "订"),
        "dong" to listOf("东", "动", "懂", "冬", "洞", "栋"),
        "dou" to listOf("都", "斗", "豆", "抖"),
        "du" to listOf("都", "读", "堵", "毒", "杜", "度"),
        "duan" to listOf("段", "断", "短"),
        "dui" to listOf("对", "队", "兑"),
        "dun" to listOf("顿", "盾", "钝"),
        "duo" to listOf("多", "夺", "躲", "舵", "朵"),

        "e" to listOf("恶", "饿", "额", "厄"),
        "en" to listOf("恩", "嗯"),

        "er" to listOf("二", "而", "儿", "耳"),

        "fa" to listOf("发", "法", "罚"),
        "fan" to listOf("范", "反", "饭", "凡", "烦", "犯", "泛", "翻", "缓", "缓"),
        "fang" to listOf("方", "房", "放", "仿", "防", "访", "纺", "访"),
        "fei" to listOf("非", "飞", "费", "肥", "沸", "废", "肺"),
        "fen" to listOf("分", "份", "粉", "纷", "份", "奋", "奋"),
        "feng" to listOf("风", "封", "峰", "疯", "丰", "凤", "奉", "缝", "缝"),
        "fo" to listOf("佛"),
        "fou" to listOf("否"),
        "fu" to listOf("不", "服", "福", "父", "付", "妇", "富", "附", "赴", "副", "抚"),

        "ga" to listOf("嘎"),
        "gai" to listOf("改", "盖"),
        "gan" to listOf("干", "敢", "感", "甘", "肝"),
        "gang" to listOf("刚", "岗", "钢", "纲", "高", "搞"),
        "gao" to listOf("高", "搞", "稿", "告", "镐"),
        "ge" to listOf("哥", "个", "各", "革", "隔"),
        "gei" to listOf("给"),
        "gen" to listOf("根", "跟"),
        "geng" to listOf("更", "耕"),
        "gong" to listOf("工", "公", "攻", "功", "供", "宫", "共", "洪", "红", "宏"),
        "gou" to listOf("构", "购", "够", "狗"),
        "gu" to listOf("古", "谷", "顾", "固", "股", "骨"),
        "gua" to listOf("瓜", "挂", "寡"),
        "guai" to listOf("怪", "拐"),
        "guan" to listOf("关", "管", "观", "官", "冠", "惯"),
        "guang" to listOf("光", "广", "光"),
        "gui" to listOf("贵", "归", "鬼", "规", "柜"),
        "gun" to listOf("滚", "棍"),
        "guo" to listOf("国", "果", "过", "锅"),

        "ha" to listOf("哈"),
        "hai" to listOf("海", "害", "还", "孩"),
        "han" to listOf("汉", "含", "寒", "旱", "汉", "喊"),
        "hang" to listOf("行", "航", "恒", "行", "巷"),
        "hao" to listOf("好", "号", "豪", "毫", "耗"),
        "he" to listOf("和", "合", "何", "河", "合", "喝", "核", "贺"),
        "hei" to listOf("黑", "嘿"),
        "hen" to listOf("很", "恨"),
        "heng" to listOf("横", "恒"),
        "hong" to listOf("红", "洪", "宏", "虹"),
        "hou" to listOf("后", "候", "厚", "侯"),
        "hu" to listOf("胡", "湖", "呼", "互", "护", "户", "户", "呼"),
        "hua" to listOf("花", "画", "化", "话", "划", "华", "滑"),
        "huai" to listOf("坏", "怀", "恢", "灰"),
        "huan" to listOf("还", "欢", "换", "环", "缓", "患"),
        "huang" to listOf("黄", "皇", "慌", "晃", "谎", "荒", "皇"),
        "hui" to listOf("会", "回", "灰", "挥", "慧", "汇", "惠", "患"),
        "hun" to listOf("混", "昏", "婚"),
        "huo" to listOf("火", "活", "或", "货", "获"),

        "ji" to listOf("几", "己", "及", "级", "即", "既", "计", "继", "寄", "技", "际", "吉", "集", "急", "寂", "疾", "激", "击", "鸡", "迹", "忌"),
        "jia" to listOf("家", "加", "假", "价", "驾", "佳", "嫁", "夹", "钾", "嘉", "稼"),
        "jian" to listOf("见", "间", "建", "件", "减", "简", "健", "检", "渐", "荐", "剑", "监", "陷", "线", "限"),
        "jiang" to listOf("将", "江", "讲", "奖", "降", "酱", "强", "抢", "墙", "强"),
        "jiao" to listOf("叫", "交", "脚", "脚", "较", "教", "角", "脚", "焦", "娇", "浇", "胶"),
        "jie" to listOf("接", "节", "解", "结", "姐", "杰", "借", "界", "戒", "接"),
        "jin" to listOf("进", "金", "今", "近", "仅", "紧", "浸", "锦", "禁", "巾", "晋"),
        "jing" to listOf("经", "进", "京", "静", "景", "竞", "警", "敬", "镜", "精", "井", "茎", "倾", "清", "情", "轻"),
        "jiong" to listOf("窘", "炯"),
        "jiu" to listOf("就", "九", "旧", "救", "久", "究", "酒", "舅", "救"),
        "ju" to listOf("具", "举", "剧", "距", "局", "居", "据", "绝", "决", "掘", "掘"),
        "juan" to listOf("卷", "捐", "捐", "券"),
        "jue" to listOf("觉", "决", "绝", "掘"),
        "jun" to listOf("军", "均", "君", "菌", "俊"),

        "ka" to listOf("卡"),
        "kai" to listOf("开", "凯"),
        "kan" to listOf("看", "干", "刊", "堪"),
        "kang" to listOf("康", "抗", "炕"),
        "kao" to listOf("考", "烤", "靠"),
        "ke" to listOf("可", "客", "科", "课", "刻", "克", "渴", "壳"),
        "ken" to listOf("肯"),
        "keng" to listOf("坑"),
        "kong" to listOf("空", "控", "孔"),
        "kou" to listOf("口", "扣", "寇"),
        "ku" to listOf("苦", "哭", "库", "枯", "裤"),
        "kua" to listOf("跨", "夸", "垮"),
        "kuai" to listOf("快", "块"),
        "kuan" to listOf("宽", "款"),
        "kuang" to listOf("况", "矿", "狂"),
        "kui" to listOf("愧", "馈"),
        "kun" to listOf("困", "昆"),
        "kuo" to listOf("括", "阔", "扩"),

        "la" to listOf("拉", "辣", "啦"),
        "lai" to listOf("来", "赖"),
        "lan" to listOf("蓝", "兰", "篮", "栏", "懒", "览"),
        "lang" to listOf("浪", "狼", "廊"),
        "lao" to listOf("老", "料", "捞", "劳", "牢"),
        "le" to listOf("了", "乐", "累", "雷"),
        "lei" to listOf("累", "雷", "泪", "类"),
        "leng" to listOf("冷"),
        "li" to listOf("里", "力", "立", "利", "理", "例", "励", "李", "礼", "历", "离", "犁", "梨", "粒"),
        "lia" to listOf("俩", "了"),
        "lian" to listOf("连", "脸", "练", "联", "恋", "廉"),
        "liang" to listOf("两", "亮", "量", "粮", "凉"),
        "liao" to listOf("料", "聊", "聊", "僚"),
        "lie" to listOf("列", "烈", "裂"),
        "lin" to listOf("林", "临", "淋", "轮"),
        "ling" to listOf("令", "零", "灵", "领", "领", "铃", "岭"),
        "liu" to listOf("六", "流", "留", "柳", "榴"),
        "lu" to listOf("路", "陆", "录", "露", "炉", "鲁"),
        "luan" to listOf("乱", "卵"),
        "lve" to listOf("略"),
        "luo" to listOf("落", "罗", "洛", "落"),

        "ma" to listOf("妈", "马", "麻", "吗", "嘛", "码"),
        "mai" to listOf("买", "卖", "迈"),
        "man" to listOf("慢", "满", "忙", "曼"),
        "mang" to listOf("忙", "芒", "盲", "忙"),
        "mao" to listOf("毛", "冒", "贸", "贸"),
        "me" to listOf("每", "美", "妹", "门", "们", "闷"),
        "mei" to listOf("每", "美", "妹", "没", "煤", "眉", "美"),
        "men" to listOf("门", "们", "闷"),
        "meng" to listOf("梦", "蒙", "孟", "猛"),
        "mi" to listOf("米", "迷", "密", "蜜", "秘", "眯"),
        "mian" to listOf("面", "棉", "免", "棉"),
        "miao" to listOf("秒", "苗", "描", "瞄"),
        "mie" to listOf("灭"),
        "min" to listOf("民", "明", "敏", "命", "命"),
        "ming" to listOf("名", "明", "命", "鸣", "瓶", "拼"),
        "miu" to listOf("谬"),
        "mo" to listOf("模", "莫", "末", "摸", "墨", "默", "陌"),
        "mou" to listOf("某"),
        "mu" to listOf("木", "目", "母", "牧", "幕", "墓"),
        "na" to listOf("那", "拿", "哪"),
        "nai" to listOf("奶", "耐"),
        "nan" to listOf("南", "男", "难", "哪", "年"),
        "nang" to listOf("囊"),
        "nao" to listOf("闹", "脑", "恼", "恼"),
        "ne" to listOf("呢"),
        "nei" to listOf("内", "耐"),
        "nen" to listOf(""),
        "neng" to listOf("能"),
        "ni" to listOf("你", "尼", "泥", "拟", "逆"),
        "nian" to listOf("年", "念"),
        "niang" to listOf("娘", "酿"),
        "niao" to listOf("鸟", "尿"),
        "nie" to listOf("捏"),
        "nin" to listOf("您"),
        "ning" to listOf("宁", "凝"),
        "niu" to listOf("牛", "扭"),
        "nong" to listOf("农", "浓"),
        "nu" to listOf("奴", "努", "怒"),
        "nv" to listOf("女"),
        "nuo" to listOf("诺", "挪", "弱"),

        "o" to listOf("哦"),
        "ou" to listOf("哦", "欧", "偶"),

        "pa" to listOf("怕", "爬", "趴"),
        "pai" to listOf("派", "排", "拍"),
        "pan" to listOf("盘", "盼", "判"),
        "pang" to listOf("旁", "庞"),
        "pao" to listOf("跑", "泡", "炮"),
        "pei" to listOf("配", "陪", "培", "佩"),
        "pen" to listOf("盆"),
        "peng" to listOf("朋", "碰", "捧", "膨"),
        "pi" to listOf("皮", "批", "匹", "屁", "劈", "皮"),
        "pian" to listOf("片", "篇", "偏"),
        "piao" to listOf("飘", "漂", "票"),
        "pie" to listOf("瞥"),
        "pin" to listOf("品", "频", "拼"),
        "ping" to listOf("平", "瓶", "评", "凭"),
        "po" to listOf("破", "坡", "婆"),
        "pou" to listOf("剖"),
        "pu" to listOf("扑", "普", "铺", "朴", "葡"),

        "qi" to listOf("其", "七", "起", "气", "齐", "奇", "七", "骑", "旗", "启", "企", "汽"),
        "qia" to listOf("恰", "卡"),
        "qian" to listOf("前", "钱", "签", "千", "浅", "欠", "迁", "潜", "陷"),
        "qiang" to listOf("强", "墙", "抢", "腔"),
        "qiao" to listOf("桥", "敲", "瞧", "悄", "峭"),
        "qie" to listOf("且", "切", "姐", "窃", "怯", "妾"),
        "qin" to listOf("亲", "秦", "勤", "琴", "秦"),
        "qing" to listOf("情", "请", "清", "轻", "青", "庆", "倾", "晴", "氰"),
        "qiong" to listOf("穷", "琼"),
        "qiu" to listOf("秋", "球", "求", "丘", "求"),
        "qu" to listOf("去", "区", "曲", "取", "趣", "驱", "屈"),
        "quan" to listOf("全", "权", "泉", "拳", "劝", "圈"),
        "que" to listOf("却", "缺", "确"),
        "qun" to listOf("群"),

        "ran" to listOf("然", "燃", "软", "染"),
        "rang" to listOf("让", "壤"),
        "rao" to listOf("绕", "扰", "饶", "扰"),
        "re" to listOf("热"),
        "ren" to listOf("人", "任", "认", "忍", "仁", "扔"),
        "reng" to listOf("仍", "扔"),
        "ri" to listOf("日", "肉"),
        "rou" to listOf("肉"),
        "ru" to listOf("如", "入", "软", "乳", "辱", "儒"),
        "rua" to listOf("撸"),
        "ruan" to listOf("软", "卵"),
        "rui" to listOf("锐", "瑞", "蕊"),
        "run" to listOf("润"),
        "ruo" to listOf("弱", "若"),

        "sa" to listOf("撒", "洒"),
        "sai" to listOf("赛", "塞", "塞"),
        "san" to listOf("三", "散", "伞"),
        "sang" to listOf("桑", "丧", "丧"),
        "sao" to listOf("扫", "嫂", "骚", "扫"),
        "se" to listOf("色", "赛"),
        "sen" to listOf("森"),
        "seng" to listOf("僧"),
        "sha" to listOf("沙", "杀", "啥", "傻", "夏", "下", "吓", "厦"),
        "shai" to listOf("晒", "摔"),
        "shan" to listOf("山", "闪", "善", "扇", "删", "删"),
        "shang" to listOf("上", "伤", "商", "厂", "让"),
        "shao" to listOf("少", "烧", "勺", "召", "稍", "梢"),
        "she" to listOf("设", "社", "舌", "蛇"),
        "shei" to listOf("谁"),
        "shen" to listOf("身", "深", "神", "伸", "审", "真", "珍"),
        "sheng" to listOf("生", "声", "胜", "升", "剩", "圣", "省"),
        "shi" to listOf("是", "时", "市", "事", "十", "十", "世", "适", "实", "试", "使", "式", "市", "始", "逝", "释", "拾", "施", "诗", "湿", "狮", "师", "尸"),
        "shou" to listOf("手", "首", "收", "受", "兽", "守", "寿", "瘦", "受"),
        "shu" to listOf("书", "数", "树", "输", "熟", "术", "束", "述", "属", "属", "束"),
        "shua" to listOf("刷"),
        "shuai" to listOf("摔", "帅", "率"),
        "shuan" to listOf("栓"),
        "shuang" to listOf("双", "霜"),
        "shui" to listOf("水", "睡", "谁"),
        "shun" to listOf("顺", "顺"),
        "shuo" to listOf("说", "缩", "弱"),

        "si" to listOf("四", "死", "丝", "思", "私", "司", "斯", "撕", "寺"),
        "song" to listOf("送", "松", "宋", "颂"),
        "sou" to listOf("搜", "宿"),
        "su" to listOf("苏", "速", "诉", "素", "宿", "宿", "俗", "肃"),
        "suan" to listOf("算", "酸"),
        "sui" to listOf("随", "岁", "碎", "虽"),
        "sun" to listOf("孙", "损", "瞬"),
        "suo" to listOf("所", "锁", "缩", "弱"),

        "ta" to listOf("他", "她", "它", "他", "塌", "塔"),
        "tai" to listOf("太", "台", "态", "态", "态"),
        "tan" to listOf("谈", "谭", "坦", "叹"),
        "tang" to listOf("唐", "堂", "汤", "糖"),
        "tao" to listOf("逃", "讨", "套", "陶", "掏", "滔"),
        "te" to listOf("特"),
        "tei" to listOf(""),
        "teng" to listOf("腾", "疼"),
        "ti" to listOf("提", "题", "体", "踢", "替"),
        "tian" to listOf("天", "添", "田", "甜"),
        "tiao" to listOf("条", "跳", "挑", "条"),
        "tie" to listOf("贴", "铁", "铁"),
        "ting" to listOf("听", "厅", "挺", "停", "亭"),
        "tong" to listOf("同", "通", "童", "痛", "统", "桶"),
        "tou" to listOf("头", "投", "透"),
        "tu" to listOf("图", "突", "吐", "土", "屠", "途", "途"),
        "tuan" to listOf("团"),
        "tui" to listOf("推", "退"),
        "tun" to listOf("吞", "屯"),
        "tuo" to listOf("托", "脱", "托", "驼"),

        "wa" to listOf("我", "挖", "瓦"),
        "wai" to listOf("外"),
        "wan" to listOf("万", "完", "玩", "晚", "碗"),
        "wang" to listOf("王", "往", "网", "望", "忘", "亡"),
        "wei" to listOf("为", "位", "伟", "未", "问", "围", "维", "危", "违", "微", "委", "尾"),
        "wen" to listOf("文", "问", "温", "闻", "稳"),
        "weng" to listOf("翁"),
        "wo" to listOf("我", "握", "卧", "乌"),
        "wo" to listOf("我", "握", "卧"),
        "wu" to listOf("无", "五", "物", "务", "误", "舞", "武", "吾", "勿", "吴"),

        "xi" to listOf("西", "习", "细", "系", "希", "吸", "喜", "洗", "席", "息", "昔", "锡"),
        "xia" to listOf("下", "夏", "吓", "峡", "瞎", "霞"),
        "xian" to listOf("先", "线", "限", "显", "鲜", "险", "现", "闲", "陷"),
        "xiang" to listOf("想", "向", "相", "香", "象", "祥", "乡", "详", "享", "项", "响"),
        "xiao" to listOf("小", "笑", "消", "晓", "校", "肖"),
        "xie" to listOf("写", "些", "些", "谢", "协", "邪"),
        "xin" to listOf("新", "心", "信", "星", "辛", "欣", "薪"),
        "xing" to listOf("行", "性", "形", "兴", "幸", "星", "醒"),
        "xiong" to listOf("兄", "凶", "胸"),
        "xiu" to listOf("休", "修", "羞", "秀"),
        "xu" to listOf("需", "许", "虚", "序", "叙", "续", "许"),
        "xuan" to listOf("选", "学", "宣", "悬", "旋", "宣"),
        "xue" to listOf("学", "雪", "血", "雪"),
        "xun" to listOf("寻", "迅", "讯", "训"),

        "ya" to listOf("呀", "雅", "亚", "压", "牙", "崖"),
        "yan" to listOf("眼", "言", "严", "岩", "延", "沿", "研", "烟", "盐", "颜", "岩", "验", "厌"),
        "yang" to listOf("样", "养", "阳", "羊", "扬", "洋", "仰", "痒"),
        "yao" to listOf("要", "药", "腰", "摇", "遥", "邀", "咬"),
        "ye" to listOf("也", "野", "业", "夜", "叶", "页"),
        "yi" to listOf("一", "以", "已", "易", "意", "义", "益", "异", "亿", "忆", "艺", "衣", "依", "医", "仪", "疑", "遗", "移", "疑"),
        "yin" to listOf("音", "因", "阴", "印", "引", "英", "婴"),
        "ying" to listOf("应", "英", "影", "硬", "赢", "营", "迎"),
        "you" to listOf("有", "又", "友", "由", "游", "幽", "邮", "优", "尤"),
        "yu" to listOf("与", "于", "余", "鱼", "雨", "玉", "育", "预", "遇", "域", "欲", "狱", "浴"),
        "yuan" to listOf("原", "远", "员", "圆", "元", "院", "源", "约", "月"),
        "yue" to listOf("月", "约", "乐", "越", "悦"),
        "yun" to listOf("云", "运", "晕", "匀"),

        "za" to listOf("杂", "砸", "昨"),
        "zai" to listOf("在", "再", "载", "灾", "宰"),
        "zan" to listOf("咱", "赞", "暂"),
        "zang" to listOf("藏", "脏"),
        "zao" to listOf("早", "造", "造", "噪", "噪"),
        "ze" to listOf("则", "责", "择", "责"),
        "zei" to listOf("贼"),
        "zen" to listOf("怎"),
        "zeng" to listOf("增", "曾"),
        "zha" to listOf("查", "扎", "炸", "站", "展", "占", "战", "章", "张", "章"),
        "zhai" to listOf("摘", "宅", "债"),
        "zhan" to listOf("站", "展", "战", "占", "章", "掌", "涨"),
        "zhang" to listOf("章", "张", "掌", "长", "帐", "涨"),
        "zhao" to listOf("找", "早", "照", "着", "招", "召", "赵"),
        "zhe" to listOf("这", "着", "遮", "折", "哲"),
        "zhei" to listOf("这"),
        "zhen" to listOf("真", "怎", "针", "振", "镇", "阵", "珍", "震"),
        "zheng" to listOf("正", "整", "政", "征", "证", "争", "睁", "争"),
        "zhi" to listOf("只", "知", "指", "志", "制", "制", "支", "治", "直", "值", "质", "植", "持", "职", "汁", "执"),
        "zhong" to listOf("中", "种", "重", "众", "钟", "终"),
        "zhou" to listOf("周", "州", "舟", "洲"),
        "zhu" to listOf("主", "住", "注", "助", "猪", "诸", "竹", "逐", "筑", "煮", "柱"),
        "zhua" to listOf("抓"),
        "zhuai" to listOf("拽"),
        "zhuan" to listOf("转", "专", "传", "钻"),
        "zhuang" to listOf("装", "壮", "撞", "状"),
        "zhui" to listOf("追", "坠"),
        "zhun" to listOf("准"),
        "zhuo" to listOf("着", "卓", "捉", "酌"),

        "zi" to listOf("子", "自", "字", "资", "紫", "兹", "滋", "滋"),
        "zong" to listOf("总", "综", "宗"),
        "zou" to listOf("走", "奏", "凑"),
        "zu" to listOf("组", "租", "祖", "阻", "足", "族"),
        "zuan" to listOf("钻", "专"),
        "zui" to listOf("最", "嘴", "罪"),
        "zun" to listOf("尊"),
        "zuo" to listOf("作", "做", "左", "坐", "座", "错"),

        // === 常用双字/多字词组（按拼音拼接） ===
        "niha" to listOf("你好"),
        "nihao" to listOf("你好", "你好"),
        "nihaoa" to listOf("你好啊"),
        "zhenshi" to listOf("真是", "真是"),
        "zhenhao" to listOf("真好", "真好"),
        "haoma" to listOf("好吗", "好吗"),
        "haoa" to listOf("好啊", "好啊"),
        "xihuan" to listOf("喜欢"),
        "haoxi" to listOf("好息"),
        "shangban" to listOf("上班"),
        "xiaban" to listOf("下班"),
        "chihe" to listOf("吃喝"),
        "chiyan" to listOf("吃饭"),
        "caizao" to listOf("在早"),
        "zhenshi" to listOf("真是"),
        "zaijian" to listOf("再见"),
        "xixi" to listOf("嘻嘻"),
        "haha" to listOf("哈哈"),
        "meimei" to listOf("妹妹", "美好"),
        "gege" to listOf("哥哥"),
        "mama" to listOf("妈妈"),
        "baba" to listOf("爸爸"),
        "xiongdi" to listOf("兄弟"),
        "jiemei" to listOf("姐妹"),
        "haoxiang" to listOf("好像", "好像"),
        "keai" to listOf("可爱"),
        "kuaile" to listOf("快乐"),
        "kaixin" to listOf("开心"),
        "xiangni" to listOf("想你", "想你"),
        "haokan" to listOf("好看"),
        "tianmi" to listOf("甜蜜"),
        "wanni" to listOf("爱你", "爱你"),
        "woaini" to listOf("我爱你"),
        "xiexie" to listOf("谢谢"),
        "bu" to listOf("不"),
        "shuijiao" to listOf("睡觉"),
        "shangchuan" to listOf("上传"),
        "xialai" to listOf("下来"),
        "yiqi" to listOf("一起"),
        "yiwang" to listOf("遗忘"),
        "xinxing" to listOf("新兴"),
        "xingfu" to listOf("幸福"),
        "xianzai" to listOf("现在"),
        "xiamen" to listOf("厦门"),
        "yiyang" to listOf("一样"),
        "yidao" to listOf("一道"),
        "yige" to listOf("一个"),
        "yitiao" to listOf("一条"),
        "yijia" to listOf("一家"),
        "yifan" to listOf("一番"),
        "yige" to listOf("一个"),
        "yitai" to listOf("一台"),
        "yiguan" to listOf("一贯"),
        "yiwai" to listOf("意外"),
        "yinggai" to listOf("应该"),
        "yiwang" to listOf("遗忘"),
        "yiwang" to listOf("遗忘"),
        "ziji" to listOf("自己"),
        "zaijian" to listOf("再见"),
        "zhenhao" to listOf("真好"),
        "zaijian" to listOf("再见"),
        "zaijian" to listOf("再见"),
        "zaijian" to listOf("再见"),
    )

    private val frequency = mutableMapOf<String, Int>()
    private var prefs: android.content.SharedPreferences? = null

    fun init(context: android.content.Context) {
        prefs = context.getSharedPreferences("pinyin_freq", android.content.Context.MODE_PRIVATE)
    }

    /** 根据拼音查询候选词 */
    fun lookup(pinyin: String): List<String> {
        val words = dict[pinyin.lowercase()] ?: emptyList()
        if (words.isEmpty()) return emptyList()
        // 按用户选择频率排序
        return words.sortedByDescending { frequency[it] ?: 0 }
    }

    /** 记录用户选择的词，提升下次排名 */
    fun recordSelection(word: String, pinyin: String) {
        frequency[word] = (frequency[word] ?: 0) + 1
        // 持久化到 SharedPreferences
        prefs?.edit()?.apply {
            putString("freq_${pinyin}_$word", frequency[word].toString())
            putString("pinyin_words_$pinyin", word)
            apply()
        }
    }

    /** 从 SharedPreferences 加载历史频率 */
    fun loadFrequency(context: android.content.Context) {
        val sp = context.getSharedPreferences("pinyin_freq", android.content.Context.MODE_PRIVATE)
        val all = sp.all ?: return
        all.forEach { (key, value) ->
            if (key.startsWith("freq_")) {
                val suffix = key.removePrefix("freq_")
                val idx = suffix.indexOf("_")
                if (idx > 0) {
                    val word = suffix.substringAfterLast("_")
                    frequency[word] = (value as? String)?.toIntOrNull() ?: 0
                }
            }
        }
    }
}